tap 'homebrew/cask'
tap "norwoodj/tap"
tap "hashicorp/tap"
tap "goreleaser/tap"
tap "adrielp/tap"
tap "aws/tap"

brew "automake"
brew "awscli"
brew "aws-sam-cli"
brew "aws-iam-authenticator"
brew "azure-cli"
brew "bashdb" 
brew "bat"
brew "clang-format"
brew "certbot"
brew "coreutils"
brew "delve"
brew "dnsmasq"
brew "bash-completion"
brew "exiftool"
brew "gcc"
brew "git"
brew "gnupg"
brew "go"
brew "goreleaser"
brew "hugo"
brew "helm"
brew "jq"
brew "kubernetes-cli"
brew "neovim"
brew "node"
brew "libksba"
brew "libtool"
brew "openssl@1.1"
brew "pkg-config"
brew "pre-commit"
brew "python@3.11"
brew "ranger"
brew "ripgrep"
brew "ruby"
brew "rust"
brew "schemacheck"
brew "stow"
brew "tfenv"
brew "tgenv"
brew "hashicorp/tap/terraform-ls"
brew "helm-docs"
brew "tmux"
brew "tree"
brew "tree-sitter"
brew "universal-ctags"
brew "wget"
brew "xz"
brew "yarn"
brew "yq"
brew "fd"
brew "starship"
brew "zellij"
brew "bat"

cask "appcleaner"
cask "brave-browser"
cask "cleanmymac"
cask "dbeaver-community"
cask "docker"
cask "google-drive"
cask "rectangle"
cask "visual-studio-code"
cask "1password"
cask "1password-cli"
cask "postman"
cask "miro"
cask "warp"
cask "notion"
cask "yubico-yubikey-manager"
cask "vivaldi"

# Optional apps you can have installed
# Some are replacements for others like: docker -> rancher
#brew "groovy"
#brew "vagrant-completion"
#brew "graphviz"
#brew "minikube"
#brew "terragrunt", args: ["ignore-dependencies"]
#brew "ansible"
#brew "gitleaks"
#brew "act"

#brew "jabba"
#brew "ethereum"
#brew "maven"


#cask "google-chrome"
#cask "vscodium"
#cask "vagrant"
#cask "rancher"
#cask "little-snitch"
#cask "drawio"
#cask "aws-vault"
#cask "krisp"

