tap "norwoodj/tap"
tap "hashicorp/tap"
tap "goreleaser/tap"
tap "adrielp/tap"
tap "aws/tap"
tap "derailed/k9s"
tap "int128/kubelogin"

brew "automake"
brew "awscli"
brew "bashdb"
brew "clang-format"
brew "certbot"
brew "coreutils"
brew "delve"
brew "dnsmasq"
brew "bash-completion"
brew "gcc"
brew "gnupg"
brew "go"
brew "goreleaser"
brew "hugo"
brew "helm"
brew "jq"
brew "k9s"
brew "kubernetes-cli"
brew "neovim"
brew "nvm"
brew "libksba"
brew "libtool"
brew "luarocks"
brew "kubelogin"
brew "pre-commit"
brew "ranger"
brew "ripgrep"
brew "rust"
brew "stow"
brew "tfenv"
brew "tgenv"
brew "tmux"
brew "tree"
brew "tree-sitter"
brew "universal-ctags"
brew "yarn"
brew "yq"
brew "fd"
brew "starship"
brew "zellij"
brew "bat"

cask "brave-browser"
cask "cleanmymac"
cask "docker"
cask "1password"
cask "1password-cli"
cask "notion"
cask "rectangle"

# brew "hashicorp/tap/terraform-ls"
# brew "helm-docs"
# brew "xz"

# cask "google-drive"
# cask "visual-studio-code"
# cask "yubico-yubikey-manager"
# cask "warp"
# cask "dbeaver-community"
